### PR TITLE
Commandline tool

### PR DESCRIPTION
**Pull request by etopeter**
Fixed broken getopts. Tested on Ubuntu16.04 with POSIX dash.
Added command line tool to set and get passwords and override key directory.

```
./encpass.sh -s secret-file.enc
./encpass.sh -g secret-file.enc
./encpass.sh -d custom-key-dir secret-file.enc
```

Added test suite that test SH BASH KSH ZSH. User input handled by expect.
```
cd tests
./suite.sh
```

### CODE REVIEW

**Comment by ahnick** [comment]
@etopeter Thanks for adding a test suite.  I don't think those rsa keys should be committed to the repo though.

**Comment by etopeter** [comment]
Yeah I was thinking about it but then it's part of test suite. Nothing secret about it. I was planning on running tests in Travis or Circle I. This way it's full independent suite.
If you still think its not good idea for RSA key I can remove it and maybe make pre test script to generate them for tests.

**Comment by ahnick** [comment]
Ah, I'm getting ahead of myself, b/c I'm planning on having it always generate keys going forward and in fact I'm planning to eliminate the entire dependency on SSH.  OpenSSL can just generate the keys and store them in a folder under the user's home directory for each and every script where you want to use encrypted passwords.  So keys in the future would be held in a directory like ~/.encpass/keys/<script_name or user-defined name>.  This has the benefit that we no longer need convert the SSH key to a PKCS8 format, we can remove the SSH dependency entirely (so it this works on machines without SSH installed), and we encourage a better security posture, so that the user is using specific keys for that script.  That way if they were ever compromised people wouldn't have to worry about other systems being compromised.  I'll be working on this change soon and get it merged and then we can look at bringing in some commandline utility support and the test suite changes you have.  If it's not too much trouble, would you be able to submit a separate pull request for what you have for the test suite so far?  I think I may want to pull that in ahead of the commandline changes?

**Comment by etopeter** [comment]
Fantastic idea with .encpass and removing dependency on ssh. I will make separate pr for test sutie. Right now test suite is using command line functionality to set passwords so I will have to refactor it to use in script function only.

**Pull request closed without merging**
